---
title: "Conflict of Interest Disclosure"
author: "Trevor Tombe"
date: 2024-11-25
output: html_document
---

The [American Economic Association](https://www.aeaweb.org/journals/policies/disclosure-policy) urges its members and other economists to disclose potential conflicts of interest through financial support (whether in monetary or non-monetary forms), paid or unpaid positions as officers, directors, or board members of non-profit or for-profit organizations, and if other interested third parties have financial, ideological, or political stakes in their work.

This is a best efforts disclosure based on the most recent five years of activity. More detail around my past professional affiliations, associations, and activities are listed on [my CV](https://www.trevortombe.com/files/CV.pdf).

---

## Sources of Financial Support

According to the AEA disclosure policy, authors "should identify each interested party from whom he or she has received significant financial support, summing to at least $10,000 in the past three years, in the form of consultant fees, retainers, grants and the like." I report these below, separating ongoing sources from one-time ad-hoc sources. For completeness, I also report potentially relevant minor sources of financial support.

**Ongoing**

- University of Calgary (2012-Present): amounts disclosed publicly according to Government of Alberta regulations
- Canadian Tax Foundation (2020-Present): services related to *Finances of the Nation*
- Financial support through various grants from the Social Sciences and Humanities Research Council (individually listed on my CV)
  - Funds cover research expenses, primarily graduate student support, and no personal financial benefit results

**Ad-Hoc (Past Six Years)**

- McGraw Hill Education (2022-25): textbook revisions and data updates
- Government of Nova Scotia (2025): consulting services
- Canadian Chamber of Commerce (2024-25): research paper and data projects
- Macdonald-Laurier Institute (2022; 2024-25): research papers on internal trade
- Government of Canada (2022-24): advisory and consulting services
- Myers LLP (2022-24): expert advice
- Government of NWT (2024): judicial compensation commission
- Government of Canada (2020): research and analysis of interprovincial trade
- Government of British Columbia (2020): research contributions to the BC Basic Income Panel (report public)
- Yukon Government (2017): member of the financial advisory panel (report public)
- Mount Royal University (2023): undergraduate program review
- Pearson Canada (2023-24): textbook revisions and data updates
- C.D. Howe Institute (2020; 2023): research papers
- Macdonald-Laurier Institute (2023): referee report
- Fraser Institute (2016-2024): referee reports and occasional author fees
- Government of Alberta (2020-21): services to the Ministry of Jobs, Economy and Innovation
- Government of Ontario (2021): research and analysis of interprovincial trade costs and policies
- Queen's University Institute on Trade Policy (2020): presentation on interprovincial trade
- Institute for Fiscal Studies and Democracy (2020): research related to federal transfer arrangements
- Canadian Economics Association (2019): Vanderkamp Prize
- Parliamentary Budget Office (2019): one-day course on federal-provincial transfers
- Government of Alberta (2019): review of internal economic analysis of carbon pricing policies
- Occasional author fees for contributions to *The Hub*, *CBC*, *Macleans*, *Alberta Views*

## Affiliations

**Current Professional Associations**

- Professor, University of Calgary
- Director of Fiscal and Economic Policy, The School of Public Policy
- Co-Director, Finances of the Nation, *Canadian Tax Journal*
- Associate Editor, *Economic Inquiry*
- Co-editor, *Canadian Public Policy*
- Board Member, The University of Calgary Faculty Association
- Board Member, Board of Trustees, Universities Academic Pension Plan
- Board Member, The Alberta Gambling Research Institute
- Member, Canadian Economics Association
- Member, American Economics Association

**Past Affiliations and Appointments**

- Editorial Advisor, *Canadian Journal of Economics*
- Board Member, ActiveCITY Calgary (2019-20)
- Member of the C.D. Howe COVID-19 Crisis Business Continuity and Trade Working Group (2020)
- Member of the Government of Alberta Market Access Task Force (2018)
- Member of the Calgary Chamber of Commerce Municipal Election Advisory Team (2017)

## Additional Disclosures

**Asset Disclosure**

- Various equity and bond holdings, largely within broadly-diversified exchange traded funds. Minor holdings of individual corporate equities within the Canadian financial and energy sectors.

**Political Activity**

- I am not a member of any political party at any level of government. Occasional (unpaid) advice and analysis has been provided to individual candidates, office holders, or staff on an ad-hoc basis representing the full spectrum of political parties in Alberta and Canada.

**Right to Review**

- No organization has a right to review or edit my published work, except when they acted as the publisher.

---


